# TODO: Remove
language: scala
sudo: true
dist: trusty

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/.coursier/cache

matrix:
  include:
  - jdk: openjdk10
    scala: 2.11.12
  - jdk: openjdk8
    scala: 2.12.10
  - env: REACTIVEMONGO_SHADED=false
    jdk: openjdk9
    scala: 2.13.1

script: ./.ci_scripts/validate.sh
