version: 2.1

commands:
  setup_sbt:
    description: Get and install SBT
    parameters:
      sbt_version:
        type: string
        default: "1.3.9"
    steps:
      - run:
          name: Setup SBT
          command: |
                    if [ ! -x ~/sbt/bin/sbt ]; then
                      cd ~/
                      curl --silent -L -o sbt.tgz https://piccolo.link/sbt-<< parameters.sbt_version >>.tgz
                      tar -xzvf sbt.tgz && rm -f sbt.tgz
                    fi
      - save_cache:
          paths:
            - ~/sbt
          key: sbt-{{ checksum "project/build.properties" }}

  build_n_tests:
    description: Build & Run tests
    steps:
      - run:
          name: Build & Run tests
          command: |
                    export PATH=$PATH:~/sbt/bin
                    export USER=`basename $HOME`
                    
                    ./.ci_scripts/validate.sh

  collect_test_reports:
    description: Collect test reports
    steps:
      - run:
          name: Collect test report
          command: |
                    mkdir test-reports
                    find . -path '*/test-reports/*' -name '*.xml' \
                      -print -exec cp {} test-reports \;
          when: always

  scala_cache:
    description: Update cache
    steps:
      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.coursier/cache
            - ~/.sbt
          key: d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}


jobs:
  scala211_jdk10:
    docker:
      - image: circleci/openjdk:10-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.11.12
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - sbt-{{ checksum "project/build.properties" }}

      - setup_sbt

      - restore_cache:
          keys:
          - d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}

      - build_n_tests

      - scala_cache

      - collect_test_reports
      - store_test_results:
          path: test-reports

  scala212_jdk8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.12.10
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - sbt-{{ checksum "project/build.properties" }}

      - setup_sbt

      - restore_cache:
          keys:
          - d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}

      - build_n_tests

      - scala_cache

      - collect_test_reports
      - store_test_results:
          path: test-reports

  scala213_jdk9:
    docker:
      - image: circleci/openjdk:9-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.13.1
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - sbt-{{ checksum "project/build.properties" }}

      - setup_sbt

      - restore_cache:
          keys:
          - d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}

      - build_n_tests

      - scala_cache

      - collect_test_reports
      - store_test_results:
          path: test-reports

  publish_snapshots:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - sbt-{{ checksum "project/build.properties" }}

      - setup_sbt

      - restore_cache:
          keys:
          - d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}

      - deploy:
          name: Publish artifacts to Sonatype Snapshots
          command: |
                    if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
                      echo "Skipped on branch ${CIRCLE_BRANCH}"
                      exit 0
                    fi
                    
                    export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
                    export PUBLISH_REPO_ID="oss.sonatype.org"
                    export PUBLISH_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots"
                    
                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
                      echo "Missing publication credentials"
                      exit 1
                    fi
                    
                    sbt +publish

      - scala_cache

workflows:
  version: 2

  main_suite:
    jobs:
      - scala211_jdk10
      - scala212_jdk8
      - scala213_jdk9
      - publish_snapshots:
          requires:
            - scala211_jdk10
            - scala212_jdk8
            - scala213_jdk9