version: 2.1

commands:
  setup_sbt:
    description: Get and install SBT
    parameters:
      sbt_version:
        type: string
        default: "1.4.7"
    steps:
      - restore_cache:
          keys:
          - &sbt_cache_key sbt-{{ checksum "project/build.properties" }}

      - run:
          name: Setup SBT
          command: |
                    if [ ! -x ~/sbt/bin/sbt ]; then
                      cd ~/
                      curl --silent -L -o sbt.tgz https://github.com/sbt/sbt/releases/download/v<< parameters.sbt_version >>/sbt-<< parameters.sbt_version >>.tgz
                      tar -xzvf sbt.tgz && rm -f sbt.tgz
                    fi

      - save_cache:
          paths:
            - ~/sbt
          key: *sbt_cache_key

  build_n_tests:
    description: Build & Run tests
    steps:
      - restore_cache:
          keys:
          - &scala_cache_key scala-{{ .Environment.CIRCLE_JOB }}-{{ checksum "version.sbt" }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}

      - run:
          name: Build & Run tests
          command: |
                    export PATH=$PATH:~/sbt/bin
                    export USER=`basename $HOME`
                    
                    ./.ci_scripts/validate.sh

      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.coursier/cache
            - ~/.sbt
          key: *scala_cache_key

  collect_test_reports:
    description: Collect test reports
    steps:
      - run:
          name: Collect test report
          command: |
                    mkdir test-reports
                    find . -path '*/test-reports/*' -name '*.xml' \
                      -print -exec cp {} test-reports \;
          when: always

  publish_snapshots:
    description: Publish snapshot artifacts to Sonatype repository
    parameters:
      shaded:
        type: boolean
        default: true
    steps:
      - deploy:
          name: Publish artifacts to Sonatype Snapshots
          command: |
                    if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
                      echo "Skipped on branch ${CIRCLE_BRANCH}"
                      exit 0
                    fi

                    V=`sbt 'show version' 2>&1 | tail -n 2 | cut -d ']' -f 2 | grep SNAPSHOT | sed -e 's/[ \t]*//g'`

                    if [ `echo "$V" | grep -- '-SNAPSHOT' | wc -l` -eq 0 ]; then
                      S=`echo "$V" | perl -pe 's/([0-9]+)$/${\($1 + 1)}-SNAPSHOT/'`
                      echo "Cannot bump $V to $S"
                      echo "version in ThisBuild := \"$S\"" > version.sbt
                    fi

                    export REACTIVEMONGO_SHADED="<< parameters.shaded >>"
                    
                    export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
                    export PUBLISH_REPO_ID="oss.sonatype.org"
                    export PUBLISH_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots"
                    
                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
                      echo "Missing publication credentials"
                      exit 1
                    fi
                    
                    sbt +publish

jobs:
  scala211_jdk11:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.11.12
    
    steps:
      - checkout
      - setup_sbt
      - build_n_tests
      - collect_test_reports
      - store_test_results:
          path: test-reports

  scala212_jdk8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.12.14
    
    steps:
      - checkout
      - setup_sbt
      - build_n_tests
      - collect_test_reports
      - store_test_results:
          path: test-reports

  scala213_jdk10:
    docker:
      - image: circleci/openjdk:10-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.13.4
    
    steps:
      - checkout
      - setup_sbt
      - build_n_tests
      - collect_test_reports
      - store_test_results:
          path: test-reports

  publish_snapshots:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo
    
    steps:
      - checkout
      - setup_sbt

      - publish_snapshots

      - publish_snapshots:
          shaded: false

  trigger_dependent_builds:
    docker:
      - image: cimg/base:2020.01

    working_directory: ~/repo

    steps:
      - run:
          name: Trigger build @ ReactiveMongo
          command: |
                    curl -X POST "https://circleci.com/api/v1.1/project/github/ReactiveMongo/ReactiveMongo/build?circle-token=${REACTIVEMONGO_API_TOKEN}"

workflows:
  version: 2

  main_suite:
    jobs:
      - scala211_jdk11
      - scala212_jdk8
      - scala213_jdk10

      - publish_snapshots:
          filters:
            branches:
              only:
                - master
          requires:
            - scala211_jdk11
            - scala212_jdk8
            - scala213_jdk10

      - trigger_dependent_builds:
          filters:
            branches:
              only:
                - master
          requires:
            - publish_snapshots
